### ISSUE TITLE
Need test case

### ISSUE THREAD

**Issue by ryepdx** [ryepdx/pyethrecover#2]
I deleted my crowdsale wallet a while ago, which makes it difficult to maintain this project as I have nothing to properly test it with. An example genesis wallet would be quite helpful!

**Comment by Dmitriy-17** [comment]
You are welcome

**Comment by ryepdx** [comment]
@Dmitriy-17 Thanks! What's the password?

**Comment by ryepdx** [comment]
Never mind, I see you've provided a MEW wallet. I've figured out a way to get my own ICO wallet file and have also added a MEW JSON test to the repo.
