### ISSUE TITLE
Not working with UTC file ?

### ISSUE THREAD

**Issue by Sovxx** [ryepdx/pyethrecover#5]
I have created a wallet with mist, and another one with myetherwaller.com using a simple 16 letter (a-z) password which I do know.

I have installed the required packages but when I type
`python pyethrecover -w [mywalletfilename] -p [mypassword]`
it only shows the elapsed time (0.1 second) and does not say the password is the right one.

**Comment by ryepdx** [comment]
This tool was designed only to work with ICO wallets, so it's not surprising it's not working with either of those! That said, I'll see what I can do to extend it to support other types of wallets.

**Comment by ryepdx** [comment]
And done.
